### ISSUE TITLE
Implement a queue for the tasks given by the player

### ISSUE THREAD

**Issue by Nimelrian** [Nimelrian/Project-Onyx#18]
A taks queue has to be implemented.
It should be implemented as a priority queue (see [cppreference - std::priority_queue](http://en.cppreference.com/w/cpp/container/priority_queue)), sorting the stored tasks by their priority.
The queue should store new tasks which have been created by the player, and assign them to character entities with the appropriate profession for the task.

It would be wise to implement the queue as a strategy, so it can be replaced with a more efficient implementation later on.

**Comment by DeKugelschieber** [comment]
Rebase in den master.
