### ISSUE TITLE
Implement a structure which stores information for a simple task

### ISSUE THREAD

**Issue by Nimelrian** [Nimelrian/Project-Onyx#19]
The structure should store the following information

* Priority
* Type: Which profession does the task belong to?
* Information about the task itself, example below (portions in parentheses are optional!)
    * Action (Tasker) Taskee (Affected) (Material) (Where) (Start-When) (End-When) (How)
        * Action: Description of task (fetch item X)
        * Taskee: Who is the asignee of the task?
        * Affected: What is affected by the task (a workshop an item is delivered to, for example)
        * Material: Tools, what can be used to fulfill the task (means of transportation)?
        * Where: Point/Line/Area/Region (Geoobject)
        * Start-/End-When: For example "Fulfill before trader departs"
        * How: fast/risky or slow/cautious

**Comment by DeKugelschieber** [comment]
Rebase in den master.
