### ISSUE TITLE
Match the current entity classes with the new requirements

### ISSUE THREAD

**Issue by Nimelrian** [Nimelrian/Project-Onyx#20]
The following requirements should be implemented in the current entity classes (Create subclasses as needed!)

* Position (Tile)
* Characters
    * Speed
    * Name
    * Stamina
    * Age
    * Needs
    * Profession(s)
    * Current task
* Items
    * Stackable
    * Multiple items should be storable in a single container (with a size limit)
    * Value and weight according to Type
        * Gold bars weigh X und have a value of Y, etc.

**Comment by DeKugelschieber** [comment]
Unassigned so that others can work on this issue.
