### ISSUE TITLE
Repository Cleanup 

### ISSUE THREAD

**Issue by Stazer** [Nimelrian/Project-Onyx#22]
- Erstellen einer Ordnerstruktur
- Entfernen aller Projektspezifischen 
- Anpassung der CMake Skripte

**Comment by DeKugelschieber** [comment]
Achtung! cleanup branch ist veraltet, aufgeräumt wurde zuletzt im master.

* Projektdateien entfernen
* Projektdateien zu gitignore hinzufügen (jeder selbst)
* nicht mehr benötigte Diagramme entfernen (docs)
