### ISSUE TITLE
InputManager auf boost umstellen

### ISSUE THREAD

**Issue by DeKugelschieber** [Nimelrian/Project-Onyx#39]
* Observer pattern entfernen
* boost für InputManager events verwenden
* multicast entfernen

**Comment by anti-freak** [comment]
Mir fällt gerade ein, dass boost signals bzw boost signals2 nicht C++11 sind. D.h. die arbeiten dort mit verschiedenen Klassen, die zwischen 0 und 10? template Parametern erwarten, statt wie jetzt eigentlich möglich, mit variadic templates zu arbeiten. Ist an sich kein größeres Problem, wollte ich nur nicht unerwähnt lassen.

**Comment by xTr1m** [comment]
Dennoch, sollten wir weiterhin boost nehmen, denn es ist zu erwarten, dass bei einer späteren boost version die syntax gleich bzw ähnlich bleibt, auch wenn sie auf variadic templates refactoren.

**Comment by anti-freak** [comment]
Ich gehe eher davon aus, dass boost signals nicht umgestellt wird, um eben ältere c++ versionen weiterhin zu supporten. Die werden eher ein neues Projekt signals11 oder so einführen. Also ja, wir können es gerne verwenden, ist aber eben nicht ganz so einfach wie mit c++11.

**Comment by DeKugelschieber** [comment]
Mal sehen wie die boost Implementierung aussieht, wenn es nicht zu viel Arbeit ist ein ähnliches C++11 System auf die Beine zu stellen könnte ich mir auch vorstellen doch was eigenes zu schreiben.

**Comment by anti-freak** [comment]
Die eigentliche Herausforderung ist ja nicht das observer pattern zu schreiben, sondern das Thread safe zu implementieren. Das ist halt letztendlich der große Vorteil von bosst::signals2

**Comment by DeKugelschieber** [comment]
Naja das oberserver pattern ist ja nicht asynchron, der Aufruf der listener findet direkt statt und läuft im Vis thread.

**Comment by xTr1m** [comment]
Wir brauchen aber auch etwas was thread safe ist, für wenn z.B. simulation events feuert, und die visualisierung davon spitz kriegen will

**Comment by DeKugelschieber** [comment]
Okay da wäre ein größeres richtiges Eventsystem aber interessant. Ich dachte erstmal nur an das InputManager Teil. Wenn das so ist, versuche ich gleich eine Komplettlösung mit boost signals zu Implementieren über die dann alle Events laufen.

**Comment by anti-freak** [comment]
Welchen Vorteil haben wir davon wenn wir EINEN Event Manager haben?
Sehe da eigentlich nur Nachteile, da wir so viel mehr Polymorphie usw. an Board holen als es eigentlich nötig wäre. Ein einfaches Signal/listener System reicht meiner Meinung nach vollkommen. Dann braucht man auch nichts rum casten und ist eigentlich genauso flexibel.

**Comment by DeKugelschieber** [comment]
Wir haben ein einheitliches System. So würde ich jetzt signals in den InputManager integrieren, beim nächsten ähnlichen Teil dann nochmal, nochmal, ...
Aber ich muss mir signals erstmal angucken. Grundsätzlich hast du recht, wenn wir vorher definieren welcher observer mit welchen listenern redet, brauchen wir kein castgedöns.

Mal in Ruhe angucken, ich bin hier auch gerade auf dem Sprung ;)
