### ISSUE TITLE
taskqueue branch löschen

### ISSUE THREAD

**Issue by DeKugelschieber** [Nimelrian/Project-Onyx#42]
Der Taskqueue branch kann gelöscht werden.

**Comment by anti-freak** [comment]
Nimelrian und ich haben gestern mal über die History geguckt. Der Branch sieht echt wirr aus, aber wurde ja eh schon in master gemerged.

https://github.com/Nimelrian/Project-Onyx/network

Vll mal in Zukunft drauf acht, das man nicht solche komischen Histories generiert (wie am Anfang bereits besprochen kein mergen beim pull, sondern rebase usw.)

**Comment by DeKugelschieber** [comment]
Wir hatten doch gesagt in die branches wird gemerged, auf den master gerebased.

**Comment by Nimelrian** [comment]
Nein, wir haben gesagt, ein Feature Branch wird regelmäßig auf den
aktuellen Mastercommit rebased und der Branch am Ende per rebase in den
Master überführt.

2015-07-30 13:28 GMT+02:00 Marvin Blum <notifications@github.com>:

**Comment by Nimelrian** [comment]
Am besten wäre es,, wenn niemand mehr einen Branch selbst in den Master
überführt und stattdessen einen Pull Request erstellt. Ich erledige dann
den Rest.

Am 30. Juli 2015 um 13:30 schrieb Sebastian Kappen <nimelriansc2@gmail.com>:

**Comment by DeKugelschieber** [comment]
Achso, die Diskussion war damals auch etwas verwirrend.
Okay dann rebase ich nur noch. Und pull requests werde ich ab jetzt sowieso erstellen.

**Comment by Nimelrian** [comment]
Erledigt.
